---
apiVersion: apps/v1
kind: Deployment                # Type of Kubernetes resource
metadata:
  name: k8ijs                     # Name of the Kubernetes resource
spec:
  replicas: 1                   # Number of pods to run at any given time
  selector:
    matchLabels:
      app: k8ijs                  # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: k8ijs
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: k8ijs
        image: k3d-registry.localhost:12345/k8ijs:v0.5
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80  # Should match the port number that the Go application listens on
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /k8ijs/health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /k8ijs/readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: k8ijs
  labels:
    app: k8ijs
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: k8ijs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress1
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /k8ijs/api
        pathType: Prefix
        backend:
          service:
            name: k8ijs
            port:
              number: 80
      - path: /k8ijs/list
        pathType: Prefix
        backend:
          service:
            name: k8ijs
            port:
              number: 80