---
apiVersion: apps/v1
kind: Deployment                # Type of Kubernetes resource
metadata:
  name: k8i                     # Name of the Kubernetes resource
spec:
  replicas: 1                   # Number of pods to run at any given time
  selector:
    matchLabels:
      app: k8i                  # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: k8i
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: k8i
        image: k3d-registry.localhost:12345/k8i:v0.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80  # Should match the port number that the Go application listens on
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /k8i/health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /k8i/readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: k8i
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8i
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /k8i/api/
        pathType: Exact
        backend:
          service:
            name: k8i
            port:
              number: 80
